name: Build and deploy LLM Overview

on:
  # Runs on pushes to leaderboard branch (for now)
  push:
    branches: ["leaderboard-page"]
  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        working-directory: ./llm-eval-website
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./llm-eval-website
          destination: ./_site
          verbose: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

